/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dbd8",
        "surface": "#f8faf7",
        "inverse-surface": "#2e3130",
        "on-primary-fixed": "#00201a",
        "tertiary-fixed-dim": "#ffb5a1",
        "on-secondary-container": "#526478",
        "on-tertiary": "#ffffff",
        "secondary-container": "#cfe2f9",
        "secondary": "#4e6073",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e9e6",
        "on-secondary": "#ffffff",
        "on-background": "#191c1b",
        "error": "#ba1a1a",
        "secondary-fixed": "#d1e4fb",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e3e0",
        "on-tertiary-fixed": "#370e04",
        "secondary-fixed-dim": "#b5c8df",
        "error-container": "#ffdad6",
        "inverse-primary": "#94d3c1",
        "primary-fixed": "#afefdd",
        "surface-bright": "#f8faf7",
        "primary-container": "#004d40",
        "outline": "#707975",
        "on-surface-variant": "#3f4945",
        "on-secondary-fixed-variant": "#36485b",
        "inverse-on-surface": "#eff1ef",
        "on-secondary-fixed": "#091d2e",
        "on-tertiary-container": "#e89f8c",
        "on-surface": "#191c1b",
        "tertiary": "#4e2013",
        "on-primary-container": "#7ebdac",
        "primary-fixed-dim": "#94d3c1",
        "outline-variant": "#bfc9c4",
        "primary": "#00342b",
        "background": "#f8faf7",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f1",
        "tertiary-container": "#693527",
        "on-tertiary-fixed-variant": "#6d382a",
        "tertiary-fixed": "#ffdbd1",
        "on-primary-fixed-variant": "#065043",
        "surface-container": "#eceeec",
        "surface-tint": "#29695b",
        "surface-variant": "#e1e3e0"
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}