@startuml FlowXacThucHD
title Sơ đồ tuần tự - Xác thực hoạt động qua QR

actor "Học sinh" as HS

participant "Giao Diện" as UI
participant "Hệ thống" as System
database "CSDL" as DB

HS -> UI : Chọn xác thực hoạt động qua QR
UI -> System : Request xác thực hoạt động

alt Chưa đăng nhập
    System --> UI : Yêu cầu đăng nhập
else Đã đăng nhập
    System -> DB : Lấy danh sách tham gia
    DB --> System : Trả dữ liệu

    System --> UI : Cho phép quét QR

    HS -> UI : Quét QR
    UI -> System : Gửi mã QR

    System -> DB : Kiểm tra QR

    alt QR không hợp lệ
        System --> UI : Báo lỗi QR
    else QR hợp lệ
        System -> System : Kiểm tra vị trí

        alt Sai vị trí
            System --> UI : Từ chối điểm danh
        else Đúng vị trí
            System -> DB : Lưu điểm danh
            DB --> System : OK
            System --> UI : Điểm danh thành công
        end
    end
end
@enduml