@startuml idk
left to right direction

actor "Học sinh" as HS

rectangle "User Case hệ thống quản lý hoạt động ngoại khóa" {

  HS --> (Đăng kí TK)
  HS --> (Đăng nhập)
  HS --> (Đăng kí hoạt động)
  HS --> (Điểm danh hoạt động)
  HS --> (Tìm kiếm hoạt động)

  (Đăng kí hoạt động) ..> (Đăng nhập) : <<include>>
  (Đăng kí hoạt động) ..> (Chọn loại hoạt động) : <<include>>
  (Đăng kí hoạt động) ..> (Chọn địa điểm) : <<include>>

  (Điểm danh hoạt động) ..> (Đăng nhập) : <<include>>
  (Điểm danh hoạt động) ..> (Xác thực địa điểm) : <<include>>
  (Điểm danh hoạt động) ..> (Xác thực điểm danh) : <<include>>

  (Tìm kiếm hoạt động) ..> (Tìm địa điểm hoạt động) : <<include>>
  (Tìm kiếm hoạt động) ..> (Tìm loại hoạt động) : <<include>>
}

@enduml