@startuml ChoiceStates

    state "Táo Xanh" as Green
    state "Táo Chín" as Ripe
    state "Táo Thối" as Rotten
    state "Ăn Táo" as Eaten
    state "Thùng rác" as Trash
    state "Còn tốt" as IsGood
    [*] --> Green

    Green --> Ripe: chín dần
    Ripe --> IsGood

    state IsGood <<choice>>

    IsGood --> Eaten: [True]
    IsGood --> Rotten: [False]

    Rotten --> Trash: Vứt vào

    Eaten --> [*]
    Trash --> [*]