@startuml QRprocess

[*] --> ScanQR

state "Quét QR" as ScanQR
state "Xử lí QR" as ProcessingQR

state "Thành công" as Success
state "Thất bại" as Fail



ScanQR --> ProcessingQR : Quét thành công

state ProcessingQR {

    [*] --> ValidateQR
    ValidateQR --> CallAPI
    CallAPI --> HandleResult
    HandleResult --> [*]
}

ProcessingQR --> Success : valid
ProcessingQR --> Fail : invalid

@enduml